packages:
  - 'packages/*'

allowBuilds:
  bufferutil: false
  esbuild: true
  unrs-resolver: true
  utf-8-validate: false

auditConfig: {}

overrides:
  'http-proxy-agent@5.0.0>@tootallnate/once': 3.0.1
  'ajv@^6.0.0': 6.14.0
  'bn.js@^5.0.0': 5.2.3
  'brace-expansion@^1.0.0': 1.1.13
  'brace-expansion@^2.0.0': 2.0.3
  'fast-xml-parser@^5.0.0': 5.7.3
  'flatted@^3.0.0': 3.4.2
  'minimatch@^3.0.0': 3.1.4
  'minimatch@^9.0.0': 9.0.7
  'picomatch@^2.0.0': 2.3.2
  'picomatch@^4.0.0': 4.0.4
  vite: 7.3.6
