packages:
  - 'packages/*'

allowBuilds:
  bufferutil: false
  esbuild: true
  unrs-resolver: true
  utf-8-validate: false

minimumReleaseAgeExclude:
  - '@solana/accounts@8.0.0'
  - '@solana/addresses@8.0.0'
  - '@solana/assertions@8.0.0'
  - '@solana/codecs-core@8.0.0'
  - '@solana/codecs-data-structures@8.0.0'
  - '@solana/codecs-numbers@8.0.0'
  - '@solana/codecs-strings@8.0.0'
  - '@solana/codecs@8.0.0'
  - '@solana/errors@8.0.0'
  - '@solana/fast-stable-stringify@8.0.0'
  - '@solana/fixed-points@8.0.0'
  - '@solana/functional@8.0.0'
  - '@solana/instruction-plans@8.0.0'
  - '@solana/instructions@8.0.0'
  - '@solana/keys@8.0.0'
  - '@solana/kit@8.0.0'
  - '@solana/nominal-types@8.0.0'
  - '@solana/offchain-messages@8.0.0'
  - '@solana/options@8.0.0'
  - '@solana/plugin-core@8.0.0'
  - '@solana/plugin-interfaces@8.0.0'
  - '@solana/program-client-core@8.0.0'
  - '@solana/programs@8.0.0'
  - '@solana/promises@8.0.0'
  - '@solana/rpc-api@8.0.0'
  - '@solana/rpc-parsed-types@8.0.0'
  - '@solana/rpc-spec-types@8.0.0'
  - '@solana/rpc-spec@8.0.0'
  - '@solana/rpc-subscriptions-api@8.0.0'
  - '@solana/rpc-subscriptions-channel-websocket@8.0.0'
  - '@solana/rpc-subscriptions-spec@8.0.0'
  - '@solana/rpc-subscriptions@8.0.0'
  - '@solana/rpc-transformers@8.0.0'
  - '@solana/rpc-transport-http@8.0.0'
  - '@solana/rpc-types@8.0.0'
  - '@solana/rpc@8.0.0'
  - '@solana/signers@8.0.0'
  - '@solana/subscribable@8.0.0'
  - '@solana/sysvars@8.0.0'
  - '@solana/transaction-confirmation@8.0.0'
  - '@solana/transaction-introspection@8.0.0'
  - '@solana/transaction-messages@8.0.0'
  - '@solana/transactions@8.0.0'

overrides:
  'http-proxy-agent@5.0.0>@tootallnate/once': 3.0.1
  'ajv@^6.0.0': 6.14.0
  'bn.js@^5.0.0': 5.2.3
  'brace-expansion@^1.0.0': 1.1.13
  'brace-expansion@^2.0.0': 2.0.3
  'fast-xml-parser@^5.0.0': 5.7.3
  'flatted@^3.0.0': 3.4.2
  'minimatch@^3.0.0': 3.1.4
  'minimatch@^9.0.0': 9.0.7
  'picomatch@^2.0.0': 2.3.2
  'picomatch@^4.0.0': 4.0.4
  vite: 7.3.6
